### ISSUE TITLE
Update dbaas controller to populate api key

### ISSUE THREAD

**Issue by wilybrace** [CrunchyData/crunchy-bridge-operator#4]
Update the DBaaS controller to obtain the api key and secret from its spec and populate a secret named `crunchy-bridge-operator-api-key`.

The example for creating from CLI:
```
kubectl create secret generic crunchy-bridge-operator-api-key \
  --from-literal="publicApiKey=<bridge_api_key>" \
  --from-literal="privateApiSecret=<bridge_api_secret>" \
  -n crunchy-bridge
```

**Comment by wilybrace** [comment]
Superceded by #7

**Comment by redhatHameed** [comment]
@wilybrace I think we still required this, WDYT? controllers required to read the API keys from secrets.

**Comment by wilybrace** [comment]
I'm commenting on #7 to reconcile my mental model and what is to be done. If the DBaaS controller will still be creating the secret based on what the DBaaS Admin provisions then I'll restore this because it still fits the updated model.

**Comment by wilybrace** [comment]
Reopened as consistent with DBaaS spec as referenced in #8

**Comment by redhatHameed** [comment]
@wilybrace closing #10 based on discussion, this will be part of the internal library.
