### ISSUE TITLE
Create a Crunchy Bridge Provider Registration ConfigMap Required by DBaaS

### ISSUE THREAD

**Issue by redhatHameed** [CrunchyData/crunchy-bridge-operator#9]
On initialization, the CrunchyBridge operator required to creates a RegistrationConfigMap that is used to inform the DBaaS operator.
![ProviderRegistrationCM](https://user-images.githubusercontent.com/41960152/121577268-5aa80d00-c9f7-11eb-82f5-96172d9aac61.png)

ConfigMap Example:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: crunchy-bridge-provider-registration
namespace: <namespace>
labels:
related-to: dbaas-operator
type: dbaas-provider-registration
data:
provider: Crunchy Bridge managed PostgreSQL
inventory_kind: CrunchyBridgeInventory
connection_kind: CrunchyBridgeConnection
credentials_fields: |
publicApiKey.name: <some field>
publicApiKey.masked: false
privateApiSecret.name: <some other field>
privateApiSecret.masked: true

```
The ConfigMap includes the name of the provider (e.g., “Crunchy Bridge managed PostgreSQL”).  The inventory_crd and connection_crd kinds and the credential_fields keys 

The Confgmap required to be created within a specified namespace for example dbaas-operator namespace and before the initialization of inventory/connection CRS or without having any prior knowledge about it.

**Comment by wilybrace** [comment]
Updated provider name in example.

**Comment by redhatHameed** [comment]
Done in #17
